import type { Intern } from "./dataType";

export const data: Intern[] = [
    {
        id: 1,
        firstName: "Алексей",
        lastName: "Иванов",
        age: 20,
        university: "МГУ",
        faculty: "Физический",
        yearOfStudy: 3,
        email: "alexey.ivanov@example.com",
        skills: ["JavaScript", "React"],
        status: "активен",
        github: "https://github.com/alexeyivanov",
        availability: "полный рабочий день",
        expectedSalary: "40000",
    },
    {
        id: 2,
        firstName: "Марина",
        lastName: "Петрова",
        age: 22,
        university: "СПбГУ",
        faculty: "Филология",
        yearOfStudy: 4,
        email: "marina.petrov@example.com",
    },
    {
        id: 3,
        firstName: "Дмитрий",
        lastName: "Сидоров",
        age: 21,
        university: "ВШЭ",
        faculty: "Экономика",
        yearOfStudy: 3,
        email: "d.sidorov@example.com",
        phone: "+7 900 123 45 67",
        status: "активен",
        skills: ["JavaScript", "React"],
        github: "https://github.com/dsidorov",
    },
    {
        id: 4,
        firstName: "Ольга",
        lastName: "Кузнецова",
        age: 19,
        university: "МГТУ",
        faculty: "Информатика",
        yearOfStudy: 2,
        email: "olga.kuznecova@example.com",
        phone: "+7 901 234 56 78",
        status: "в ожидании",
        skills: ["Python", "Django", "Git"],
        github: "https://github.com/okuznecova",
        preferredTechStack: ["Python", "Django"],
        availability: "неполный рабочий день",
        expectedSalary: "35000",
    },
    {
        id: 5,
        firstName: "Игорь",
        lastName: "Морозов",
        age: 23,
        university: "СПбГУ",
        faculty: "Прикладная математика",
        yearOfStudy: 5,
        email: "igor.morozov@example.com",
        status: "завершён",
        skills: ["C++", "Python", "Algorithms"],
        availability: "полный рабочий день",
        github: "https://github.com/igor-morozov",
    },
    {
        id: 6,
        firstName: "Екатерина",
        lastName: "Лебедева",
        age: 20,
        university: "МФТИ",
        faculty: "Физика",
        yearOfStudy: 2,
        email: "ekaterina.lebedeva@example.com",
        status: "активен",
        skills: ["C#", ".NET", "SQL"],
        preferredTechStack: ["C#", "SQL"],
        availability: "полный рабочий день",
    },
    {
        id: 7,
        firstName: "Сергей",
        lastName: "Воробьёв",
        age: 21,
        university: "МГУ",
        faculty: "Прикладная информатика",
        yearOfStudy: 4,
        email: "sergey.vorobev@example.com",
        phone: "+7 905 555 44 33",
        status: "активен",
        skills: ["JavaScript", "Node.js", "React"],
        github: "https://github.com/sergeyvorobev",
        availability: "полный рабочий день",
        expectedSalary: "45000",
    },
    {
        id: 8,
        firstName: "Наталья",
        lastName: "Смирнова",
        age: 19,
        university: "СПбГУ",
        faculty: "Математика",
        yearOfStudy: 1,
        email: "natalya.smirnova@example.com",
        status: "в ожидании",
        skills: ["Python", "Machine Learning"],
    },
    {
        id: 9,
        firstName: "Владимир",
        lastName: "Козлов",
        age: 22,
        university: "ВШЭ",
        faculty: "Экономика",
        yearOfStudy: 3,
        email: "vladimir.kozlov@example.com",
        phone: "+7 912 345 67 89",
        status: "активен",
        skills: ["SQL", "Excel"],
        preferredTechStack: ["SQL"],
        availability: "неполный рабочий день",
    },
    {
        id: 10,
        firstName: "Анастасия",
        lastName: "Новикова",
        age: 20,
        university: "МГТУ",
        faculty: "Информатика",
        yearOfStudy: 2,
        email: "anastasia.novikova@example.com",
        skills: ["Java", "Spring"],
        status: "активен",
    },
    {
        id: 11,
        firstName: "Максим",
        lastName: "Крылов",
        age: 23,
        university: "МГУ",
        faculty: "Прикладная математика",
        yearOfStudy: 5,
        email: "maksim.krylov@example.com",
        phone: "+7 999 888 77 66",
        status: "завершён",
        skills: ["C++", "Algorithms", "Data Structures"],
        availability: "полный рабочий день",
        github: "https://github.com/maksimkrylov",
    },
    {
        id: 12,
        firstName: "Елена",
        lastName: "Васильева",
        age: 21,
        university: "МФТИ",
        faculty: "Физика",
        yearOfStudy: 4,
        email: "elena.vasilieva@example.com",
        skills: ["Python", "Data Analysis"],
        status: "активен",
        preferredTechStack: ["Python", "Pandas"],
        availability: "неполный рабочий день",
    },
    {
        id: 13,
        firstName: "Илья",
        lastName: "Михайлов",
        age: 20,
        university: "СПбГУ",
        faculty: "Информатика",
        yearOfStudy: 2,
        email: "ilya.mikhailov@example.com",
        skills: ["JavaScript", "Vue.js"],
        status: "в ожидании",
        github: "https://github.com/ilyamikhailov",
    },
    {
        id: 14,
        firstName: "Виктория",
        lastName: "Зайцева",
        age: 19,
        university: "ВШЭ",
        faculty: "Экономика",
        yearOfStudy: 1,
        email: "victoria.zaiceva@example.com",
        skills: ["Excel", "SQL"],
        status: "активен",
    },
    {
        id: 15,
        firstName: "Роман",
        lastName: "Кузьмин",
        age: 22,
        university: "МГУ",
        faculty: "Прикладная информатика",
        yearOfStudy: 3,
        email: "roman.kuzmin@example.com",
        phone: "+7 911 222 33 44",
        skills: ["Java", "Spring", "Hibernate"],
        status: "активен",
        availability: "полный рабочий день",
    },
    {
        id: 16,
        firstName: "Алина",
        lastName: "Григорьева",
        age: 20,
        university: "МГТУ",
        faculty: "Информатика",
        yearOfStudy: 2,
        email: "alina.grigorieva@example.com",
        skills: ["C#", ".NET"],
        status: "в ожидании",
        github: "https://github.com/alinagrigorieva",
    },
    {
        id: 17,
        firstName: "Денис",
        lastName: "Лебедев",
        age: 23,
        university: "СПбГУ",
        faculty: "Физика",
        yearOfStudy: 5,
        email: "denis.lebedev@example.com",
        skills: ["C++", "Python"],
        status: "активен",
    },
    {
        id: 18,
        firstName: "Оксана",
        lastName: "Морозова",
        age: 21,
        university: "ВШЭ",
        faculty: "Экономика",
        yearOfStudy: 3,
        email: "oksana.morozova@example.com",
        skills: ["SQL", "Excel"],
        status: "активен",
    },
    {
        id: 19,
        firstName: "Константин",
        lastName: "Волков",
        age: 22,
        university: "МГУ",
        faculty: "Прикладная математика",
        yearOfStudy: 4,
        email: "konstantin.volkov@example.com",
        skills: ["Matlab", "Python"],
        status: "активен",
    },
    {
        id: 20,
        firstName: "Татьяна",
        lastName: "Соколова",
        age: 20,
        university: "МФТИ",
        faculty: "Физика",
        yearOfStudy: 3,
        email: "tatiana.sokolova@example.com",
        skills: ["Python", "Machine Learning"],
        status: "активен",
    },
    {
        id: 21,
        firstName: "Василий",
        lastName: "Ефимов",
        age: 21,
        university: "СПбГУ",
        faculty: "Прикладная математика",
        yearOfStudy: 4,
        email: "vasiliy.efimov@example.com",
        skills: ["C++", "Алгоритмы"],
        status: "активен",
        availability: "полный рабочий день",
    },
    {
        id: 22,
        firstName: "Юлия",
        lastName: "Тихонова",
        age: 19,
        university: "МГУ",
        faculty: "Физика",
        yearOfStudy: 2,
        email: "yulia.tikhonova@example.com",
        skills: ["JavaScript", "Vue.js"],
        status: "ожидает",
    },
    {
        id: 23,
        firstName: "Никита",
        lastName: "Мельников",
        age: 23,
        university: "ВШЭ",
        faculty: "Экономика",
        yearOfStudy: 5,
        email: "nikita.melnikov@example.com",
        skills: ["SQL", "Excel"],
        status: "активен",
        availability: "неполный рабочий день",
    },
    {
        id: 24,
        firstName: "Евгения",
        lastName: "Киселева",
        age: 20,
        university: "МГТУ",
        faculty: "Информатика",
        yearOfStudy: 3,
        email: "evgenia.kiseleva@example.com",
        skills: ["Python", "Django"],
        status: "активен",
        github: "https://github.com/evgeniakiseleva",
        availability: "полный рабочий день",
    },
    {
        id: 25,
        firstName: "Артём",
        lastName: "Гусев",
        age: 22,
        university: "МФТИ",
        faculty: "Прикладная математика",
        yearOfStudy: 4,
        email: "artem.gusev@example.com",
        skills: ["C++", "Машинное обучение"],
        status: "ожидает",
    },
    {
        id: 26,
        firstName: "Ксения",
        lastName: "Федорова",
        age: 21,
        university: "СПбГУ",
        faculty: "Физика",
        yearOfStudy: 4,
        email: "ksenia.fedorova@example.com",
        skills: ["JavaScript", "React", "TypeScript"],
        status: "активен",
        github: "https://github.com/kseniafedorova",
        availability: "полный рабочий день",
        expectedSalary: "42000",
    },
    {
        id: 27,
        firstName: "Арина",
        lastName: "Морозова",
        age: 21,
        university: "СПбГУ",
        faculty: "Экономика",
        yearOfStudy: 4,
        email: "arina.morozova@example.com",
        skills: ["SQL", "Excel", "Power BI"],
        status: "активен",
        availability: "неполный рабочий день",
    },
    {
        id: 28,
        firstName: "Максим",
        lastName: "Павлов",
        age: 22,
        university: "МГУ",
        faculty: "Прикладная математика",
        yearOfStudy: 5,
        email: "maksim.pavlov@example.com",
        skills: ["C++", "Python", "Машинное обучение"],
        status: "завершил",
        github: "https://github.com/maksimpavlov",
    },
    {
        id: 29,
        firstName: "Екатерина",
        lastName: "Соколова",
        age: 20,
        university: "МФТИ",
        faculty: "Физика",
        yearOfStudy: 3,
        email: "ekaterina.sokolova@example.com",
        skills: ["Python", "Анализ данных"],
        status: "активен",
        availability: "полный рабочий день",
    },
    {
        id: 30,
        firstName: "Игорь",
        lastName: "Лебедев",
        age: 23,
        university: "ВШЭ",
        faculty: "Информатика",
        yearOfStudy: 5,
        email: "igor.lebedev@example.com",
        skills: ["JavaScript", "React", "Node.js"],
        status: "активен",
        github: "https://github.com/igorlebedev",
        availability: "полный рабочий день",
    },
    {
        id: 31,
        firstName: "Марина",
        lastName: "Кузьмина",
        age: 19,
        university: "СПбГУ",
        faculty: "Филология",
        yearOfStudy: 2,
        email: "marina.kuzmina@example.com",
        skills: ["Копирайтинг", "SEO"],
        status: "ожидает",
    },
    {
        id: 32,
        firstName: "Роман",
        lastName: "Орлов",
        age: 21,
        university: "МГУ",
        faculty: "Прикладная информатика",
        yearOfStudy: 3,
        email: "roman.orlov@example.com",
        skills: ["Java", "Spring"],
        status: "активен",
        availability: "полный рабочий день",
    },
    {
        id: 33,
        firstName: "Дарья",
        lastName: "Козлова",
        age: 20,
        university: "МГТУ",
        faculty: "Информатика",
        yearOfStudy: 2,
        email: "darya.kozlova@example.com",
        skills: ["Python", "Django"],
        status: "активен",
    },
    {
        id: 34,
        firstName: "Сергей",
        lastName: "Никитин",
        age: 23,
        university: "СПбГУ",
        faculty: "Математика",
        yearOfStudy: 5,
        email: "sergey.nikitin@example.com",
        skills: ["C++", "Алгоритмы"],
        status: "завершил",
        github: "https://github.com/sergeynikitin",
    },
    {
        id: 35,
        firstName: "Александра",
        lastName: "Волкова",
        age: 20,
        university: "ВШЭ",
        faculty: "Экономика",
        yearOfStudy: 3,
        email: "alexandra.volkova@example.com",
        skills: ["Excel", "SQL"],
        status: "активен",
        availability: "неполный рабочий день",
    },
    {
        id: 36,
        firstName: "Виктор",
        lastName: "Смирнов",
        age: 22,
        university: "МГУ",
        faculty: "Прикладная информатика",
        yearOfStudy: 4,
        email: "viktor.smirnov@example.com",
        skills: ["JavaScript", "React", "TypeScript"],
        status: "активен",
        github: "https://github.com/viktorsmirnov",
    },
    {
        id: 37,
        firstName: "Ольга",
        lastName: "Зайцева",
        age: 21,
        university: "МФТИ",
        faculty: "Физика",
        yearOfStudy: 4,
        email: "olga.zaiceva@example.com",
        skills: ["Python", "Машинное обучение"],
        status: "активен",
        availability: "полный рабочий день",
    },
    {
        id: 38,
        firstName: "Иван",
        lastName: "Тимофеев",
        age: 23,
        university: "СПбГУ",
        faculty: "Прикладная математика",
        yearOfStudy: 5,
        email: "ivan.timofeev@example.com",
        skills: ["C++", "Python", "Алгоритмы"],
        status: "завершил",
    },
    {
        id: 39,
        firstName: "Мария",
        lastName: "Петрова",
        age: 19,
        university: "МГУ",
        faculty: "Филология",
        yearOfStudy: 2,
        email: "maria.petrova@example.com",
        skills: ["Копирайтинг", "SEO"],
        status: "ожидает",
    },
    {
        id: 40,
        firstName: "Дмитрий",
        lastName: "Васильев",
        age: 22,
        university: "ВШЭ",
        faculty: "Экономика",
        yearOfStudy: 4,
        email: "dmitry.vasiliev@example.com",
        skills: ["SQL", "Excel", "Power BI"],
        status: "активен",
        availability: "полный рабочий день",
    },
];
